FROM ruby:3.3.5-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev \
    curl nodejs npm libvips pkg-config postgresql-client sudo && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN mkdir -p /bundle && chmod 777 /bundle

WORKDIR /rails

ENV BUNDLE_PATH=/bundle \
    BUNDLE_APP_CONFIG=/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

COPY Gemfile Gemfile.lock ./

ENV RAILS_ENV=development

EXPOSE 3000

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]