services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db_test
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: knajping_development
      DB_USERNAME: postgres
      DB_PASSWORD: password
      TEST_DB_HOST: db_test
      TEST_DB_PORT: 5432
      TEST_DB_NAME: knajping_test
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: password
      BUNDLE_PATH: /bundle
      BUNDLE_APP_CONFIG: /bundle
    volumes:
      - .:/rails
      - bundle_cache:/bundle
      - knajping_storage:/rails/storage
      - ./config/master.key:/rails/config/master.key:ro
    command: sh -c "bundle install && bundle exec rails db:migrate && bundle exec rails db:test:prepare && ./bin/rails server -b 0.0.0.0 -p 3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: knajping_development
    ports:
      - "5432:5432"

  db_test:
    image: postgres:15
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: knajping_test
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  postgres_test_data:
  knajping_storage:
  bundle_cache:
