services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev # Using a development-specific Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/knajping_development
      BUNDLE_PATH: /bundle # Set bundle path to our volume
      BUNDLE_APP_CONFIG: /bundle
    volumes:
      - .:/rails
      - bundle_cache:/bundle # Mount the bundle cache correctly
      - knajping_storage:/rails/storage
      - ./config/master.key:/rails/config/master.key:ro
    command: sh -c "bundle install && bundle exec rails db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: knajping_development
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  knajping_storage:
  bundle_cache:
