default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['TEST_DB_HOST'] %>
  port: <%= ENV['TEST_DB_PORT'] || 5432 %>
  database: <%= ENV['TEST_DB_NAME'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: knajping_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: knajping_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: knajping_production_cable
    migrations_paths: db/cable_migrate
